image: node:lts

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - cd client
          - npm ci
          - npm run build:beta
          - npm run build:prod
