image: node:14

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - cd client
          - npm install
          - npm run build:beta
          - npm run build:prod
